### ISSUE TITLE
Distinct value in one-to-many relationship

### ISSUE THREAD

**Issue by viniciusffj** [six2six/fixture-factory#65]
I'm using Fixture Factory and I have a doubt.

When using a one-to-many relatorionship we must do this:
``` add("skills", has(2).of(Skill.class, "valid")); ```

But this generates duplicated skills and I don't want then to be repeated.

Is there an option to generate no duplicated value?

Thanks!

**Comment by nykolaslima** [comment]
@viniciusffj we've implemented a `uniqueRandom` functions that generates unique values #70.

I believe we can close this PR, what do you think?

**Comment by viniciusffj** [comment]
@nykolaslima Yes, thanks for the attention.

**Comment by nykolaslima** [comment]
Thank you!
