### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by Entea** [six2six/fixture-factory#92]
Thanks for the cool library!

Would be cool if the library could create enums:

```
public enum Foo {
   Bar, Baz;
}
```

```
Fixture.of(Foo.class).addTemplate(new Rule() {{
    oneOf(Bar, Baz);
}});
```

```
Fixture.from(Foo.class).gimme("random");
```

**Comment by atif-github-venture** [comment]
Hi.. can I work on this solution, will you be accepting the PR in time?
Our team needs this for an academic project.

**Comment by nykolaslima** [comment]
Hello @atif-github-venture 
You can get a random value from enum using `random` method:
```
Fixture.of(User.class).addTemplate("valid", new Rule() {{
  add("group", random(Group.class));
}});
```

Or just call the [`EnumFunction`](https://github.com/six2six/fixture-factory/blob/b6f23f236e6c4014a1d8ecfa36b6a0f535c4c3f7/src/main/java/br/com/six2six/fixturefactory/function/impl/EnumFunction.java) directly:
```
List<Group> values = new EnumFunction(Group.class, 1).generateValue()
```

**Comment by atif-github-venture** [comment]
@nykolaslima my request was more on working for a solution than knowing how to alternatively use this library. But appreciate  the inputs :)

**Comment by nykolaslima** [comment]
@atif-github-venture I believe no one is maintaining this project anymore.
Maybe a better option would be to fork the project and implement the new features.

**Comment by atif-github-venture** [comment]
Well in that case its a bummer for me.. coz we really need someone/admin to review and accept the PR/solution so we can account for same in our academic project.
Thank you for sharing @nykolaslima
